version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: impa-nginx
    ports:
      - "8080:80"
    volumes:
      - ../public:/var/www/html/public
      - ../src:/var/www/html/src
      - ../config:/var/www/html/config
      - ../vendor:/var/www/html/vendor
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - impa-network

  php:
    image: php:8.2-fpm-alpine
    container_name: impa-php
    volumes:
      - ../public:/var/www/html/public
      - ../src:/var/www/html/src
      - ../config:/var/www/html/config
      - ../vendor:/var/www/html/vendor
    networks:
      - impa-network

  # Futuro: MySQL/PostgreSQL aqui

networks:
  impa-network:
    driver: bridge