version: '3.8'

services:
  web:
    image: php:8.1-apache
    volumes:
      - ../public:/var/www/html
      - ../inc:/var/www/inc
      - ../src:/var/www/src
      - ../views:/var/www/views
    ports:
      - "8080:80"
    environment:
      - TZ=America/Sao_Paulo

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: impa
      POSTGRES_PASSWORD: impa123
      POSTGRES_DB: impa_portal
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
